# Generated by Django 5.0.1 on 2024-02-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Id",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200, null=True)),
                ("name", models.CharField(max_length=200, null=True)),
                ("isin", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Indoor", "Indoor"), ("Outdoor", "Outdoor")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector", models.CharField(max_length=200, null=True)),
                ("industry", models.CharField(max_length=200, null=True)),
                ("gicSector", models.CharField(max_length=200, null=True)),
                ("gicGroup", models.CharField(max_length=200, null=True)),
                ("gicIndustry", models.CharField(max_length=200, null=True)),
                ("gicSubIndustry", models.CharField(max_length=200, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scores.id",
                    ),
                ),
            ],
        ),
    ]
