# Generated by Django 5.0.1 on 2024-02-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0002_id_alter_product_category_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sectors",
                to="scores.id",
            ),
        ),
    ]
