# Generated by Django 5.0.1 on 2024-02-07 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0004_alter_sector_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Id",
            new_name="Identification",
        ),
    ]
