# Generated by Django 5.0.1 on 2024-03-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0005_rename_id_identification"),
    ]

    operations = [
        migrations.CreateModel(
            name="qualdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=200, null=True)),
                ("exchange", models.CharField(max_length=200, null=True)),
                ("beta", models.FloatField(null=True)),
                ("mcap", models.FloatField(null=True)),
                ("sector", models.CharField(max_length=200, null=True)),
                ("dividendyield", models.FloatField(null=True)),
            ],
        ),
    ]
