# Generated by Django 5.0.1 on 2024-03-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0006_qualdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualdata",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
