# Generated by Django 5.0.1 on 2024-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0007_qualdata_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualdata",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
