# Generated by Django 5.0.1 on 2024-06-13 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0008_qualdata_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qualdata",
            old_name="dividendyield",
            new_name="dividendYield",
        ),
    ]
