# Generated by Django 5.0.1 on 2024-11-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0009_rename_dividendyield_qualdata_dividendyield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("date", models.CharField(max_length=25)),
                ("close", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
